// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtZ1RB64jmVNmMmFieDwUEsnmXaJ-nYU',
    appId: '1:1082480107918:web:93d567c9d0eb5efe4d04df',
    messagingSenderId: '1082480107918',
    projectId: 'personaltrainerhelper-88108',
    authDomain: 'personaltrainerhelper-88108.firebaseapp.com',
    storageBucket: 'personaltrainerhelper-88108.appspot.com',
    measurementId: 'G-DBTE30YPYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxtzPdZUim0p_rQuEVb3DsgBI99kHav8',
    appId: '1:1082480107918:android:6069e504b0f5682b4d04df',
    messagingSenderId: '1082480107918',
    projectId: 'personaltrainerhelper-88108',
    storageBucket: 'personaltrainerhelper-88108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKnLoUjaaNMUXjc9sP4DKdUO3qhzprfI',
    appId: '1:1082480107918:ios:d824b3b3d8d7b2bc4d04df',
    messagingSenderId: '1082480107918',
    projectId: 'personaltrainerhelper-88108',
    storageBucket: 'personaltrainerhelper-88108.appspot.com',
    iosClientId: '1082480107918-bai2561na0umgl584topf6plpjn9cm3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKnLoUjaaNMUXjc9sP4DKdUO3qhzprfI',
    appId: '1:1082480107918:ios:d824b3b3d8d7b2bc4d04df',
    messagingSenderId: '1082480107918',
    projectId: 'personaltrainerhelper-88108',
    storageBucket: 'personaltrainerhelper-88108.appspot.com',
    iosClientId: '1082480107918-bai2561na0umgl584topf6plpjn9cm3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pthApp',
  );
}
